import type {
  Account,
  Bill,
  Card,
  Category,
  Debt,
  FixedFlowEntry,
  Investment,
  MonthlyPlan,
  NavItem,
  PlannedPurchase,
  Settings,
  Transaction,
  UserProfile,
} from "@/types/finance";

export const referenceDate = "2026-04-14";

function createCategoryBudgets(
  overrides: Partial<
    Record<
      "market" | "fuel" | "moto" | "volei" | "clothes" | "bills" | "debts" | "investments",
      number
    >
  >,
) {
  return [
    { id: "budget-market", name: "Mercado", kind: "expense" as const, planned: overrides.market ?? 0 },
    { id: "budget-fuel", name: "Gasolina", kind: "expense" as const, planned: overrides.fuel ?? 0 },
    { id: "budget-moto", name: "Moto", kind: "expense" as const, planned: overrides.moto ?? 0 },
    { id: "budget-volei", name: "Volei", kind: "expense" as const, planned: overrides.volei ?? 0 },
    { id: "budget-clothes", name: "Roupas", kind: "expense" as const, planned: overrides.clothes ?? 0 },
    { id: "budget-bills", name: "Contas a pagar", kind: "expense" as const, planned: overrides.bills ?? 0 },
    { id: "budget-debts", name: "Dividas", kind: "debt" as const, planned: overrides.debts ?? 0 },
    {
      id: "budget-investments",
      name: "Investimentos",
      kind: "investment" as const,
      planned: overrides.investments ?? 0,
    },
  ];
}

function createMonthlyPlanEntry(
  monthLabel: string,
  fixedIncomePlanned: number,
  variableIncomePlanned: number,
  fixedExpensesPlanned: number,
  variableExpensesPlanned: number,
  debtTarget: number,
  categoryBudgets: ReturnType<typeof createCategoryBudgets>,
): MonthlyPlan {
  return {
    monthLabel,
    fixedIncomePlanned,
    variableIncomePlanned,
    fixedExpensesPlanned,
    variableExpensesPlanned,
    investmentTarget: 0,
    debtTarget,
    extraIncomeGoal: variableIncomePlanned,
    categoryBudgets,
    reserveGoals: [
      {
        id: "reserve-first-investment",
        name: "Primeiro aporte",
        target: 500,
        current: 0,
        deadline: "2026-08-30",
        priority: "Média",
      },
    ],
  };
}

function createAmountMap(entries: Array<[string, number]>) {
  return Object.fromEntries(entries);
}

export const navItems: NavItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    shortLabel: "Resumo",
    description: "Visao geral do mes e alertas criticos",
  },
  {
    id: "transactions",
    label: "Transacoes",
    shortLabel: "Movs",
    description: "Lancamentos, filtros e cadastro rapido",
  },
  {
    id: "planning",
    label: "Planejamento",
    shortLabel: "Kanban",
    description: "Compras futuras e prioridades em colunas",
  },
  {
    id: "bills",
    label: "Contas",
    shortLabel: "Contas",
    description: "Contas, recorrencias e dividas no mesmo fluxo",
  },
  {
    id: "reports",
    label: "Relatorios",
    shortLabel: "Dados",
    description: "Categorias, evolucao e comportamento do mes",
  },
  {
    id: "settings",
    label: "Configuracoes",
    shortLabel: "Ajustes",
    description: "Metas, contas padrao e arquitetura futura",
  },
];

export const profile: UserProfile = {
  name: "Caio",
  email: "caio@monex.local",
  focus: "Organizar o inicio do emprego novo e sair das dividas",
};

export const accounts: Account[] = [
  {
    id: "acc-main",
    name: "Conta Principal",
    type: "Conta corrente",
    initialBalance: -2800,
    currentBalance: 370,
    isActive: true,
  },
  {
    id: "acc-wallet",
    name: "Carteira",
    type: "Dinheiro fisico",
    initialBalance: 120,
    currentBalance: 120,
    isActive: true,
  },
  {
    id: "acc-reserve",
    name: "Reserva",
    type: "Conta de reserva",
    initialBalance: 0,
    currentBalance: 0,
    isActive: true,
  },
];

export const cards: Card[] = [
  {
    id: "card-nubank",
    name: "Nubank",
    issuer: "Nubank",
    brand: "Mastercard",
    lastDigits: "4701",
    accentColor: "#7a2cff",
    availableMode: "both",
    closingDay: 7,
    dueDay: 15,
    creditLimit: 470,
    linkedAccountId: "acc-main",
    isActive: true,
  },
  {
    id: "card-c6",
    name: "C6",
    issuer: "C6 Bank",
    brand: "Mastercard",
    lastDigits: "8426",
    accentColor: "#111111",
    availableMode: "debit",
    closingDay: 12,
    dueDay: 20,
    creditLimit: 0,
    linkedAccountId: "acc-main",
    isActive: true,
  },
];

export const categories: Category[] = [
  { id: "cat-salary", name: "Salario", type: "income", color: "#1f8f6b" },
  { id: "cat-extra", name: "Renda extra", type: "income", color: "#2dbe7f" },
  { id: "cat-market", name: "Mercado", type: "expense", color: "#e56767" },
  { id: "cat-fuel", name: "Gasolina", type: "expense", color: "#f59f46" },
  { id: "cat-bills", name: "Contas a pagar", type: "expense", color: "#3c8ef7" },
  { id: "cat-debt", name: "Dividas", type: "expense", color: "#7c3aed" },
  { id: "cat-moto", name: "Moto", type: "expense", color: "#1d63cf" },
  { id: "cat-volei", name: "Volei", type: "expense", color: "#0f766e" },
  { id: "cat-clothes", name: "Roupas", type: "expense", color: "#d946ef" },
  { id: "cat-invest", name: "Investimentos", type: "expense", color: "#3977ff" },
];

export const transactions: Transaction[] = [
  {
    id: "tx-1",
    title: "Entregas semana 1",
    type: "income",
    amount: 500,
    date: "2026-02-06",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-2",
    title: "Entregas semana 2",
    type: "income",
    amount: 500,
    date: "2026-02-13",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-3",
    title: "Entregas semana 3",
    type: "income",
    amount: 500,
    date: "2026-02-20",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-4",
    title: "Entregas semana 4",
    type: "income",
    amount: 500,
    date: "2026-02-27",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-5",
    title: "Mercado do mes",
    type: "expense",
    amount: 280,
    date: "2026-02-11",
    categoryId: "cat-market",
    categoryName: "Mercado",
    paymentMethod: "cash",
    status: "paid",
    expenseKind: "variable",
    accountId: "acc-wallet",
  },
  {
    id: "tx-6",
    title: "Gasolina",
    type: "expense",
    amount: 150,
    date: "2026-02-18",
    categoryId: "cat-fuel",
    categoryName: "Gasolina",
    paymentMethod: "debit_card",
    status: "paid",
    expenseKind: "variable",
    cardId: "card-c6",
    cardMode: "debit",
    accountId: "acc-main",
  },
  {
    id: "tx-7",
    title: "Entregas semana 1",
    type: "income",
    amount: 500,
    date: "2026-03-06",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-8",
    title: "Entregas semana 2",
    type: "income",
    amount: 500,
    date: "2026-03-13",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-9",
    title: "Entregas semana 3",
    type: "income",
    amount: 500,
    date: "2026-03-20",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-10",
    title: "Entregas semana 4",
    type: "income",
    amount: 500,
    date: "2026-03-27",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-11",
    title: "Mercado do mes",
    type: "expense",
    amount: 310,
    date: "2026-03-12",
    categoryId: "cat-market",
    categoryName: "Mercado",
    paymentMethod: "cash",
    status: "paid",
    expenseKind: "variable",
    accountId: "acc-wallet",
  },
  {
    id: "tx-12",
    title: "Gasolina",
    type: "expense",
    amount: 165,
    date: "2026-03-18",
    categoryId: "cat-fuel",
    categoryName: "Gasolina",
    paymentMethod: "debit_card",
    status: "paid",
    expenseKind: "variable",
    cardId: "card-c6",
    cardMode: "debit",
    accountId: "acc-main",
  },
  {
    id: "tx-13",
    title: "Entregas semana 1",
    type: "income",
    amount: 500,
    date: "2026-04-04",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-14",
    title: "Entregas semana 2",
    type: "income",
    amount: 500,
    date: "2026-04-11",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "received",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-15",
    title: "Mercado do mes",
    type: "expense",
    amount: 160,
    date: "2026-04-12",
    categoryId: "cat-market",
    categoryName: "Mercado",
    paymentMethod: "cash",
    status: "paid",
    expenseKind: "variable",
    accountId: "acc-wallet",
  },
  {
    id: "tx-16",
    title: "Gasolina",
    type: "expense",
    amount: 95,
    date: "2026-04-05",
    categoryId: "cat-fuel",
    categoryName: "Gasolina",
    paymentMethod: "debit_card",
    status: "paid",
    expenseKind: "variable",
    cardId: "card-c6",
    cardMode: "debit",
    accountId: "acc-main",
  },
  {
    id: "tx-17",
    title: "Gasolina extra",
    type: "expense",
    amount: 70,
    date: "2026-04-13",
    categoryId: "cat-fuel",
    categoryName: "Gasolina",
    paymentMethod: "pix",
    status: "paid",
    expenseKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-18",
    title: "Primeiro salario emprego novo",
    type: "income",
    amount: 1200,
    date: "2026-05-05",
    categoryId: "cat-salary",
    categoryName: "Salario",
    paymentMethod: "bank_transfer",
    status: "planned",
    incomeKind: "fixed_expected",
    accountId: "acc-main",
  },
  {
    id: "tx-19",
    title: "Entregas previstas maio",
    type: "income",
    amount: 800,
    date: "2026-05-28",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "planned",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-20",
    title: "Salario previsto junho",
    type: "income",
    amount: 2200,
    date: "2026-06-05",
    categoryId: "cat-salary",
    categoryName: "Salario",
    paymentMethod: "bank_transfer",
    status: "planned",
    incomeKind: "fixed_expected",
    accountId: "acc-main",
  },
  {
    id: "tx-21",
    title: "Entregas previstas junho",
    type: "income",
    amount: 800,
    date: "2026-06-28",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "planned",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-22",
    title: "Salario previsto julho",
    type: "income",
    amount: 2200,
    date: "2026-07-05",
    categoryId: "cat-salary",
    categoryName: "Salario",
    paymentMethod: "bank_transfer",
    status: "planned",
    incomeKind: "fixed_expected",
    accountId: "acc-main",
  },
  {
    id: "tx-23",
    title: "Entregas previstas julho",
    type: "income",
    amount: 800,
    date: "2026-07-28",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "planned",
    incomeKind: "variable",
    accountId: "acc-main",
  },
  {
    id: "tx-24",
    title: "Salario previsto agosto",
    type: "income",
    amount: 2500,
    date: "2026-08-05",
    categoryId: "cat-salary",
    categoryName: "Salario",
    paymentMethod: "bank_transfer",
    status: "planned",
    incomeKind: "fixed_expected",
    accountId: "acc-main",
  },
  {
    id: "tx-25",
    title: "Entregas previstas agosto",
    type: "income",
    amount: 800,
    date: "2026-08-28",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    paymentMethod: "pix",
    status: "planned",
    incomeKind: "variable",
    accountId: "acc-main",
  },
];

export const bills: Bill[] = [
  {
    id: "bill-1",
    title: "Mensalidade Vapo",
    amount: 180,
    categoryId: "cat-bills",
    categoryName: "Contas a pagar",
    dueDate: "2026-04-20",
    priority: "Urgente",
    isRecurring: false,
    status: "pending",
    plannedPaymentMethod: "pix",
    notes: "Pagar nas proximas semanas para nao acumular",
  },
];

export const debts: Debt[] = [
  {
    id: "debt-1",
    name: "500 mae",
    description: "Valor emprestado pela mae",
    totalAmount: 500,
    paidAmount: 0,
    remainingAmount: 500,
    totalInstallments: 5,
    paidInstallments: 0,
    installmentAmount: 100,
    nextDueDate: "2026-04-28",
    priority: "Média",
    status: "active",
    plannedPaymentMethod: "cash",
  },
  {
    id: "debt-2",
    name: "500 vo",
    description: "Valor emprestado pelo avo",
    totalAmount: 500,
    paidAmount: 0,
    remainingAmount: 500,
    totalInstallments: 5,
    paidInstallments: 0,
    installmentAmount: 100,
    nextDueDate: "2026-05-05",
    priority: "Média",
    status: "active",
    plannedPaymentMethod: "cash",
  },
  {
    id: "debt-3",
    name: "750 PicPay",
    description: "Saldo ja fechado no credito",
    totalAmount: 750,
    paidAmount: 0,
    remainingAmount: 750,
    totalInstallments: 3,
    paidInstallments: 0,
    installmentAmount: 250,
    nextDueDate: "2026-04-18",
    priority: "Urgente",
    status: "active",
    plannedPaymentMethod: "pix",
  },
  {
    id: "debt-4",
    name: "400 C6",
    description: "Outra divida de cartao ja existente",
    totalAmount: 400,
    paidAmount: 0,
    remainingAmount: 400,
    totalInstallments: 3,
    paidInstallments: 0,
    installmentAmount: 150,
    nextDueDate: "2026-04-25",
    priority: "Alta",
    status: "active",
    plannedPaymentMethod: "pix",
  },
  {
    id: "debt-5",
    name: "110 SHPL",
    description: "Valor emprestado do torneio para devolver",
    totalAmount: 110,
    paidAmount: 0,
    remainingAmount: 110,
    totalInstallments: 1,
    paidInstallments: 0,
    installmentAmount: 110,
    nextDueDate: "2026-04-30",
    priority: "Alta",
    status: "active",
    plannedPaymentMethod: "pix",
  },
];

export const plannedPurchases: PlannedPurchase[] = [
  {
    id: "plan-1",
    name: "Freio moto",
    description: "Nao e emergencia, mas precisa resolver logo",
    estimatedValue: 180,
    priority: "Alta",
    desiredDate: "2026-04-26",
    targetWeek: "Semana 4",
    boardColumn: "this_month",
    savedAmount: 0,
    suggestedPeriodAmount: 90,
    status: "active",
    plannedPaymentMethod: "pix",
  },
  {
    id: "plan-2",
    name: "Bola Vapo",
    description: "Bola Penalty 8.0 para o time de volei",
    estimatedValue: 350,
    priority: "Média",
    desiredDate: "2026-05-08",
    targetMonth: "2026-05",
    boardColumn: "next_month",
    savedAmount: 0,
    suggestedPeriodAmount: 120,
    status: "planned",
    plannedPaymentMethod: "cash",
  },
  {
    id: "plan-3",
    name: "Banco moto",
    description: "Troca importante, mas sem urgencia imediata",
    estimatedValue: 260,
    priority: "Média",
    desiredDate: "2026-05-18",
    targetMonth: "2026-05",
    boardColumn: "next_month",
    savedAmount: 0,
    suggestedPeriodAmount: 100,
    status: "planned",
    plannedPaymentMethod: "pix",
  },
  {
    id: "plan-4",
    name: "Roupas novas",
    description: "Pode comprar no cartao ou no dinheiro quando encaixar",
    estimatedValue: 300,
    priority: "Baixa",
    desiredDate: "2026-05-22",
    targetMonth: "2026-05",
    boardColumn: "next_month",
    savedAmount: 0,
    suggestedPeriodAmount: 0,
    status: "planned",
    plannedPaymentMethod: "card",
    plannedCardId: "card-nubank",
  },
  {
    id: "plan-5",
    name: "Carenagem moto",
    description: "Pode esperar um pouco mais",
    estimatedValue: 450,
    priority: "Adiável",
    desiredDate: "2026-06-20",
    targetMonth: "2026-06",
    boardColumn: "later",
    savedAmount: 0,
    suggestedPeriodAmount: 80,
    status: "idea",
    plannedPaymentMethod: "card",
    plannedCardId: "card-nubank",
  },
];

export const investments: Investment[] = [];

export const fixedFlowEntries: FixedFlowEntry[] = [
  {
    id: "fixed-income-salary",
    section: "Ganhos",
    title: "Salario fixo",
    kind: "income",
    categoryId: "cat-salary",
    categoryName: "Salario",
    amountByMonth: createAmountMap([
      ["2026-05", 1200],
      ["2026-06", 2200],
      ["2026-07", 2200],
      ["2026-08", 2500],
      ["2026-09", 2500],
      ["2026-10", 2500],
      ["2026-11", 2500],
      ["2026-12", 2500],
    ]),
    completedMonths: [],
    paymentMethod: "bank_transfer",
    accountId: "acc-main",
    notes: "Primeiro salario parcial em maio e reajuste previsto depois da fase inicial.",
  },
  {
    id: "fixed-income-deliveries",
    section: "Ganhos",
    title: "Entregas",
    kind: "income",
    categoryId: "cat-extra",
    categoryName: "Renda extra",
    amountByMonth: createAmountMap([
      ["2026-01", 2000],
      ["2026-02", 2000],
      ["2026-03", 2000],
      ["2026-04", 1000],
      ["2026-05", 800],
      ["2026-06", 800],
      ["2026-07", 800],
      ["2026-08", 800],
      ["2026-09", 800],
      ["2026-10", 800],
      ["2026-11", 800],
      ["2026-12", 800],
    ]),
    completedMonths: ["2026-02", "2026-03", "2026-04"],
    paymentMethod: "pix",
    accountId: "acc-main",
    notes: "Historico forte nos ultimos meses e meta mais conservadora daqui para frente.",
  },
  {
    id: "fixed-expense-vapo",
    section: "Gastos fixos",
    title: "Mensalidade Vapo",
    kind: "expense",
    categoryId: "cat-bills",
    categoryName: "Contas a pagar",
    amountByMonth: createAmountMap([
      ["2026-04", 180],
      ["2026-05", 180],
      ["2026-06", 180],
      ["2026-07", 180],
      ["2026-08", 180],
      ["2026-09", 180],
      ["2026-10", 180],
      ["2026-11", 180],
      ["2026-12", 180],
    ]),
    completedMonths: [],
    paymentMethod: "pix",
    accountId: "acc-main",
    notes: "Compromisso que precisa aparecer facil para nao passar do prazo.",
  },
  {
    id: "fixed-debt-mother",
    section: "Dividas e repasses",
    title: "Mae",
    kind: "expense",
    categoryId: "cat-debt",
    categoryName: "Dividas",
    amountByMonth: createAmountMap([
      ["2026-04", 100],
      ["2026-05", 100],
      ["2026-06", 100],
      ["2026-07", 100],
      ["2026-08", 100],
    ]),
    completedMonths: [],
    paymentMethod: "cash",
    accountId: "acc-wallet",
    notes: "Quitacao planejada em cinco repasses de R$ 100.",
  },
  {
    id: "fixed-debt-grandfather",
    section: "Dividas e repasses",
    title: "Vo",
    kind: "expense",
    categoryId: "cat-debt",
    categoryName: "Dividas",
    amountByMonth: createAmountMap([
      ["2026-05", 100],
      ["2026-06", 100],
      ["2026-07", 100],
      ["2026-08", 100],
      ["2026-09", 100],
    ]),
    completedMonths: [],
    paymentMethod: "cash",
    accountId: "acc-wallet",
    notes: "Mais cinco repasses previstos para encerrar essa devolucao.",
  },
  {
    id: "fixed-debt-picpay",
    section: "Dividas e repasses",
    title: "PicPay",
    kind: "expense",
    categoryId: "cat-debt",
    categoryName: "Dividas",
    amountByMonth: createAmountMap([
      ["2026-04", 250],
      ["2026-05", 250],
      ["2026-06", 250],
    ]),
    completedMonths: [],
    paymentMethod: "pix",
    accountId: "acc-main",
    notes: "Divida do cartao ja fechada e tratada em tres parcelas iguais.",
  },
  {
    id: "fixed-debt-c6",
    section: "Dividas e repasses",
    title: "C6",
    kind: "expense",
    categoryId: "cat-debt",
    categoryName: "Dividas",
    amountByMonth: createAmountMap([
      ["2026-04", 150],
      ["2026-05", 150],
      ["2026-06", 100],
    ]),
    completedMonths: [],
    paymentMethod: "pix",
    accountId: "acc-main",
    notes: "Valor ajustado para fechar os R$ 400 da divida do cartao.",
  },
  {
    id: "fixed-debt-shpl",
    section: "Dividas e repasses",
    title: "SHPL",
    kind: "expense",
    categoryId: "cat-debt",
    categoryName: "Dividas",
    amountByMonth: createAmountMap([["2026-04", 110]]),
    completedMonths: [],
    paymentMethod: "pix",
    accountId: "acc-main",
    notes: "Devolucao unica do valor pego emprestado do torneio.",
  },
];

export const settings: Settings = {
  fixedSalaryExpected: 2200,
  monthlyInvestmentTarget: 0,
  defaultAccountId: "acc-main",
  defaultCardId: "card-nubank",
  weekStartDay: 1,
  extraIncomeGoal: 800,
};

export const monthlyPlansByMonth: Record<string, MonthlyPlan> = {
  "2026-04": createMonthlyPlanEntry(
    "Abril 2026",
    0,
    2000,
    180,
    450,
    610,
    createCategoryBudgets({
      market: 220,
      fuel: 200,
      moto: 180,
      volei: 0,
      clothes: 0,
      bills: 180,
      debts: 610,
      investments: 0,
    }),
  ),
  "2026-05": createMonthlyPlanEntry(
    "Maio 2026",
    1200,
    800,
    180,
    650,
    500,
    createCategoryBudgets({
      market: 250,
      fuel: 220,
      moto: 260,
      volei: 350,
      clothes: 300,
      bills: 180,
      debts: 500,
      investments: 0,
    }),
  ),
  "2026-06": createMonthlyPlanEntry(
    "Junho 2026",
    2200,
    800,
    180,
    720,
    450,
    createCategoryBudgets({
      market: 300,
      fuel: 250,
      moto: 450,
      volei: 0,
      clothes: 0,
      bills: 180,
      debts: 450,
      investments: 0,
    }),
  ),
  "2026-07": createMonthlyPlanEntry(
    "Julho 2026",
    2200,
    800,
    180,
    650,
    350,
    createCategoryBudgets({
      market: 300,
      fuel: 250,
      moto: 0,
      volei: 0,
      clothes: 0,
      bills: 180,
      debts: 350,
      investments: 0,
    }),
  ),
  "2026-08": createMonthlyPlanEntry(
    "Agosto 2026",
    2500,
    800,
    180,
    650,
    250,
    createCategoryBudgets({
      market: 320,
      fuel: 250,
      moto: 0,
      volei: 0,
      clothes: 0,
      bills: 180,
      debts: 250,
      investments: 0,
    }),
  ),
};

export const monthlyPlan: MonthlyPlan = monthlyPlansByMonth["2026-04"];
